openapi: 3.2.0
info:
  title: Partnerize Brands Attribution … Campaign Transaction…
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- description: 'Transaction Queries (TQs) allow Partners to raise disputes about conversions with a Brand.

    There are three types of Transaction Queries:

    - Untracked: A conversion has not been tracked.

    - Incorrect Commission: A conversion does not have the correct Partner commission value.

    - Declined: The Brand has rejected a conversion.'
  name: Campaign Transaction Queries
paths:
  /campaign/{campaign_id}/tq:
    get:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: Filter by the ID of a transaction query
        example: 1l1000532
        in: query
        name: transaction_query_id
        required: false
        schema:
          type: string
      - description: Filter by the type
        example: untracked
        in: query
        name: transaction_query_type
        required: false
        schema:
          type: string
      - description: Filter by a partner reference
        example: A200FG1
        in: query
        name: publisher_reference
        required: false
        schema:
          type: string
      - description: Filter by a conversion reference
        example: AF222PO
        in: query
        name: conversion_reference
        required: false
        schema:
          type: string
      - description: Filter by a conversion date
        example: '2017-01-01 00:00:00'
        in: query
        name: conversion_date_time
        required: false
        schema:
          type: string
      - description: Filter by the ID of a campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: Filter by the current state
        example: pending
        in: query
        name: current_state
        required: false
        schema:
          type: string
      - description: Field to filter the date range on
        example: created_at
        in: query
        name: date_range_column
        required: false
        schema:
          type: string
      - description: Start of a date range
        example: '2017-01-01 00:00:00'
        in: query
        name: date_range_start
        required: false
        schema:
          type: string
      - description: End of a date range
        example: '2017-12-30 00:00:00'
        in: query
        name: date_range_end
        required: false
        schema:
          type: string
      - description: Natural language representation of a date range
        example: last 10 days
        in: query
        name: text_date
        required: false
        schema:
          type: string
      - description: Field to sort the results by
        example: created_at
        in: query
        name: sort_column
        required: false
        schema:
          type: string
      - description: Direction to sort the results by
        example: ASC
        in: query
        name: order_by
        required: false
        schema:
          type: string
      - description: Download the results as a CSV file
        example: 'true'
        in: query
        name: tq_export
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    count: 5
                    execution_time: 0.08001 seconds
                    filters: {}
                    sort:
                      column: created_at
                      direction: ASC
                    transaction_queries:
                    - transaction_query:
                        actions_available:
                        - approve
                        - reject
                        campaign:
                          advertiser_id: 10l110
                          campaign_id: 10l176
                          created: '2017-01-01 00:00:00'
                          created_by: 11l16829
                          default_override: '1'
                          hidden_campaign: y
                          last_modified: '2017-01-01 00:00:00'
                          network_fee: null
                          payment_date: null
                          reporting_timezone: Australia/Sydney
                          status: a
                          title: Example Campaign
                          type: sale
                          vertical_id: 10
                          week_start: monday
                        campaign_id: 10l176
                        camref: hrDu67
                        conversion_currency: GBP
                        conversion_date_time: '2017-01-01 00:00:00'
                        conversion_id: 111111l304972
                        conversion_reference: AUTO-5953bd8c5fe7b
                        conversion_value: 9729
                        created_at: '2017-01-01 00:00:00'
                        current_state: pending
                        expected_commission: 907.43
                        notes: Quam ex rerum nulla enim.
                        publisher:
                          agreed_to_latest_network_terms: y
                          created: '2017-01-01 00:00:00'
                          created_by: 11l16829
                          name: Example Partner
                          network_id: 1l1000003
                          network_status: a
                          publisher_id: 1l1007802
                          ref_terms_and_conditions_locale_id: 1l100284
                          reporting_timezone: Australia/Sydney
                          signup_ip: 127.0.0.1
                          week_start: saturday
                        publisher_id: 1l1007802
                        publisher_reference: rerum
                        state_history:
                          conversion_expected_commission: 837.49
                          conversion_item_id: 111111l1107235
                          created_at: '2017-01-01 00:00:00'
                          notes: Quidem facilis iste sapiente reiciendis.
                          state: pending
                          transaction_query_id: 111111l10
                          transaction_query_state_id: 111111l9
                          user_id: 11l16829
                        transaction_query_id: 111111l10
                        transaction_query_type: untracked
                        updated_at: '2017-02-01 00:00:00'
              schema:
                properties:
                  count:
                    type: number
                  execution_time:
                    type: string
                  filters:
                    description: The filters applied to the results
                    properties: {}
                    type: object
                  sort:
                    properties:
                      column:
                        description: The column the results are sorted by
                        type: string
                      direction:
                        description: The direction the results are sorted in
                        enum:
                        - ASC
                        - DESC
                        type: string
                    type: object
                  transaction_queries:
                    items:
                      $ref: '#/components/schemas/Transaction_Query_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Campaign Transaction Queries
      description: Return the details of all Transaction Queries created on a campaign.
      operationId: List all Transaction Queries
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Generate a CSV file in a job and send the result to this email address, helpful when processing takes too long for a normal download
      summary: List all Transaction Queries for a Campaign
  /campaign/{campaign_id}/tq/{transaction_query_id}/approve:
    post:
      parameters:
      - description: ID of a Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: ID of the Transaction Query
        example: 1l1000532
        in: path
        name: transaction_query_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.08001 seconds
                    transaction_query:
                      actions_available: []
                      campaign:
                        advertiser_id: 10l110
                        campaign_id: 10l176
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        default_override: '1'
                        hidden_campaign: y
                        last_modified: '2017-01-01 00:00:00'
                        network_fee: null
                        payment_date: null
                        reporting_timezone: Australia/Sydney
                        status: a
                        title: Example Campaign
                        type: sale
                        vertical_id: 10
                        week_start: monday
                      campaign_id: 10l176
                      camref: hrDu67
                      conversion_currency: GBP
                      conversion_date_time: '2017-01-01 00:00:00'
                      conversion_id: 111111l304972
                      conversion_reference: AUTO-5953bd8c5fe7b
                      conversion_value: 9729
                      created_at: '2017-01-01 00:00:00'
                      current_state: pending
                      expected_commission: 907.43
                      notes: Quam ex rerum nulla enim.
                      publisher:
                        agreed_to_latest_network_terms: y
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        name: Example Partner
                        network_id: 1l1000003
                        network_status: a
                        publisher_id: 1l1007802
                        ref_terms_and_conditions_locale_id: 1l100284
                        reporting_timezone: Australia/Sydney
                        signup_ip: 127.0.0.1
                        week_start: saturday
                      publisher_id: 1l1007802
                      publisher_reference: rerum
                      state_history:
                        conversion_expected_commission: 837.49
                        conversion_item_id: 111111l1107235
                        created_at: '2017-01-01 00:00:00'
                        notes: Quidem facilis iste sapiente reiciendis.
                        state: pending
                        transaction_query_id: 111111l10
                        transaction_query_state_id: 111111l9
                        user_id: 11l16829
                      transaction_query_id: 111111l10
                      transaction_query_type: untracked
                      updated_at: '2017-02-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Transaction_Query_Wrapper'
          description: OK
        '400':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: Requested action around TQs that does not exists
                      type: '400'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Bad Request
        '404':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: The TQ ID supplied for this action does not match an existing TQ.
                      type: '404'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Not Found
      tags:
      - Campaign Transaction Queries
      description: Approve a single Transaction Query. Only Transaction Queries with a status of pending can be approved.
      operationId: Approve a Transaction Query
      requestBody:
        content:
          application/json:
            schema:
              example:
                expected_commission: 907.43
              properties:
                expected_commission:
                  description: The commission that the conversion should have after being approved
                  type: number
              type: object
      summary: Approve a Transaction Query
  /campaign/{campaign_id}/tq/{transaction_query_id}/pend:
    post:
      parameters:
      - description: ID of a Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: ID of the Transaction Query
        example: 1l1000532
        in: path
        name: transaction_query_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.08001 seconds
                    transaction_query:
                      actions_available:
                      - approve
                      - reject
                      campaign:
                        advertiser_id: 10l110
                        campaign_id: 10l176
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        default_override: '1'
                        hidden_campaign: y
                        last_modified: '2017-01-01 00:00:00'
                        network_fee: null
                        payment_date: null
                        reporting_timezone: Australia/Sydney
                        status: a
                        title: Example Campaign
                        type: sale
                        vertical_id: 10
                        week_start: monday
                      campaign_id: 10l176
                      camref: hrDu67
                      conversion_currency: GBP
                      conversion_date_time: '2017-01-01 00:00:00'
                      conversion_id: 111111l304972
                      conversion_reference: AUTO-5953bd8c5fe7b
                      conversion_value: 9729
                      created_at: '2017-01-01 00:00:00'
                      current_state: pending
                      expected_commission: 907.43
                      notes: Quam ex rerum nulla enim.
                      publisher:
                        agreed_to_latest_network_terms: y
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        name: Example Partner
                        network_id: 1l1000003
                        network_status: a
                        publisher_id: 1l1007802
                        ref_terms_and_conditions_locale_id: 1l100284
                        reporting_timezone: Australia/Sydney
                        signup_ip: 127.0.0.1
                        week_start: saturday
                      publisher_id: 1l1007802
                      publisher_reference: rerum
                      state_history:
                        conversion_expected_commission: 837.49
                        conversion_item_id: 111111l1107235
                        created_at: '2017-01-01 00:00:00'
                        notes: Quidem facilis iste sapiente reiciendis.
                        state: pending
                        transaction_query_id: 111111l10
                        transaction_query_state_id: 111111l9
                        user_id: 11l16829
                      transaction_query_id: 111111l10
                      transaction_query_type: untracked
                      updated_at: '2017-02-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Transaction_Query_Wrapper'
          description: OK
        '400':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: Requested action around TQs that does not exists
                      type: '400'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Bad Request
        '404':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: The TQ ID supplied for this action does not match an existing TQ.
                      type: '404'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Not Found
      tags:
      - Campaign Transaction Queries
      description: Pend a single Transaction Query. Only Transaction Queries with a status of rejected can be pended.
      operationId: Pend a Transaction Query
      summary: Pend a Transaction Query
  /campaign/{campaign_id}/tq/{transaction_query_id}/reject:
    post:
      parameters:
      - description: ID of a campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: ID of the transaction query
        example: 1l1000532
        in: path
        name: transaction_query_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.08001 seconds
                    transaction_query:
                      actions_available:
                      - pend
                      campaign:
                        advertiser_id: 10l110
                        campaign_id: 10l176
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        default_override: '1'
                        hidden_campaign: y
                        last_modified: '2017-01-01 00:00:00'
                        network_fee: null
                        payment_date: null
                        reporting_timezone: Australia/Sydney
                        status: a
                        title: Example Campaign
                        type: sale
                        vertical_id: 10
                        week_start: monday
                      campaign_id: 10l176
                      camref: hrDu67
                      conversion_currency: GBP
                      conversion_date_time: '2017-01-01 00:00:00'
                      conversion_id: 111111l304972
                      conversion_reference: AUTO-5953bd8c5fe7b
                      conversion_value: 9729
                      created_at: '2017-01-01 00:00:00'
                      current_state: pending
                      expected_commission: 907.43
                      notes: Quam ex rerum nulla enim.
                      publisher:
                        agreed_to_latest_network_terms: y
                        created: '2017-01-01 00:00:00'
                        created_by: 11l16829
                        name: Example Partner
                        network_id: 1l1000003
                        network_status: a
                        publisher_id: 1l1007802
                        ref_terms_and_conditions_locale_id: 1l100284
                        reporting_timezone: Australia/Sydney
                        signup_ip: 127.0.0.1
                        week_start: saturday
                      publisher_id: 1l1007802
                      publisher_reference: rerum
                      state_history:
                        conversion_expected_commission: 837.49
                        conversion_item_id: 111111l1107235
                        created_at: '2017-01-01 00:00:00'
                        notes: Quidem facilis iste sapiente reiciendis.
                        state: pending
                        transaction_query_id: 111111l10
                        transaction_query_state_id: 111111l9
                        user_id: 11l16829
                      transaction_query_id: 111111l10
                      transaction_query_type: untracked
                      updated_at: '2017-02-01 00:00:00'
              schema:
                $ref: '#/components/schemas/Transaction_Query_Wrapper'
          description: OK
        '400':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: Requested action around TQs that does not exists
                      type: '400'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Bad Request
        '404':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: The TQ ID supplied for this action does not match an existing TQ.
                      type: '404'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Not Found
      tags:
      - Campaign Transaction Queries
      description: Reject a single Transaction Query. Only Transaction Queries with a status of pending can be rejected.
      operationId: Reject a Transaction Query
      requestBody:
        content:
          application/json:
            schema:
              example:
                reason: Example reason
              properties:
                reason:
                  description: The reason for rejecting the Transaction Query
                  type: string
              type: object
      summary: Reject a Transaction Query
  /campaign/{campaign_id}/tq/process:
    post:
      parameters:
      - description: ID of a Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.08001 seconds
                    job:
                      completed_at: '2016-04-07 04:21:52'
                      created_at: '2016-04-07 04:21:51'
                      created_by: '300621'
                      created_by_uri: ''
                      estimated_completion: null
                      job_id: 111111l470
                      percentage_complete: 100
                      reference: null
                      response: /job/111111l1177306/response.json
                      response_within_retention: true
                      status: complete
                      time_elapsed: 0
                      update: /job/111111l1177306.json
              schema:
                properties:
                  execution_time:
                    type: string
                  job:
                    properties:
                      completed_at:
                        type:
                        - string
                        - 'null'
                      created_at:
                        type: string
                      created_by:
                        description: ID of the user who created the job
                        type: string
                      created_by_uri:
                        type: string
                      estimated_completion:
                        type:
                        - string
                        - 'null'
                      job_id:
                        description: ID of the job
                        type: string
                      percentage_complete:
                        type: number
                      reference:
                        type:
                        - string
                        - 'null'
                      response:
                        description: The raw response
                        type:
                        - string
                        - 'null'
                      response_within_retention:
                        type: boolean
                      status:
                        enum:
                        - complete
                        - created
                        - active
                        type: string
                      time_elapsed:
                        type: number
                      update:
                        description: The update URI
                        type:
                        - string
                        - 'null'
                    type: object
                type: object
          description: OK
        '400':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    error:
                      message: Requested action around TQs that does not exists
                      type: '400'
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
          description: Bad Request
      tags:
      - Campaign Transaction Queries
      description: Process multiple Transaction Queries in a single API call. The same rules as approving, rejecting and pending single Transaction Queries apply. The actions are processed asynchronously and the Job endpoint must be polled to find out when all have been completed.
      operationId: Bulk process Transaction Queries
      requestBody:
        content:
          application/json:
            schema:
              example:
                transaction_queries:
                - new_expected_commission: 13.45
                  new_reason: Example reason
                  new_state: pending
                  transaction_query_id: 1l1000532
              properties:
                transaction_queries:
                  items:
                    properties:
                      new_expected_commission:
                        description: expected commission value after the state change
                        type: number
                      new_reason:
                        description: reason for the state change
                        type: string
                      new_state:
                        $ref: '#/components/schemas/Transaction_Query_State'
                      transaction_query_id:
                        description: ID of the Transaction Query
                        type: string
                  type: array
              type: object
      summary: Bulk processing of Transaction Queries
components:
  schemas:
    Transaction_Query_State_History:
      properties:
        conversion_expected_commission:
          type: number
        conversion_item_id:
          type: string
        created_at:
          type: string
        notes:
          type: string
        state:
          $ref: '#/components/schemas/Transaction_Query_State'
        transaction_query_id:
          type: string
        transaction_query_state_id:
          type: string
        user_id:
          type: string
      type: object
    Transaction_Query_Wrapper:
      properties:
        transaction_query:
          $ref: '#/components/schemas/Transaction_Query'
      type: object
    Status:
      type: string
      enum:
      - a
      - p
      - r
      - n
    Timezones:
      enum:
      - Australia/Sydney
      - UTC
      - Europe/London
      - CET
      - GMT
      type: string
    Transaction_Query_Type:
      enum:
      - untracked
      - incorrect_commission
      - declined
      type: string
    Currency:
      enum:
      - GBP
      - USD
      - EUR
      - JPY
      type: string
    Transaction_Query:
      properties:
        campaign:
          properties:
            advertiser_id:
              type: string
            campaign_id:
              type: string
            created:
              type: string
            created_by:
              type: string
            default_override:
              type: string
            hidden_campaign:
              $ref: '#/components/schemas/YesOrNo'
            last_modified:
              type: string
            network_fee:
              type: string
            payment_date:
              type: string
            reporting_timezone:
              $ref: '#/components/schemas/Timezones'
            status:
              $ref: '#/components/schemas/Status'
            title:
              type: string
            type:
              type: string
            vertical_id:
              type: number
            week_start:
              type: string
          type: object
        campaign_id:
          type: string
        camref:
          type: string
        conversion_currency:
          $ref: '#/components/schemas/Currency'
        conversion_date_time:
          type: string
        conversion_id:
          type: string
        conversion_reference:
          type: string
        conversion_value:
          type: number
        created_at:
          type: string
        current_state:
          $ref: '#/components/schemas/Transaction_Query_State'
        expected_commission:
          type: number
        notes:
          type: string
        publisher:
          properties:
            agreed_to_latest_network_terms:
              $ref: '#/components/schemas/YesOrNo'
            created:
              type: string
            created_by:
              type: string
            name:
              type: string
            network_id:
              type: string
            network_status:
              type: string
            publisher_id:
              type: string
            ref_terms_and_conditions_locale_id:
              type: string
            reporting_timezone:
              $ref: '#/components/schemas/Timezones'
            signup_ip:
              type: string
            week_start:
              type: string
          type: object
        publisher_id:
          type: string
        publisher_reference:
          type: string
        state_history:
          $ref: '#/components/schemas/Transaction_Query_State_History'
        transaction_query_id:
          type: string
        transaction_query_type:
          $ref: '#/components/schemas/Transaction_Query_Type'
        updated_at:
          type: string
      type: object
    YesOrNo:
      enum:
      - y
      - n
      type: string
    Transaction_Query_State:
      enum:
      - pending
      - approved
      - rejected
      type: string
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
