openapi: 3.2.0
info:
  title: Partnerize Brands Attribution Jobs API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- name: Jobs
paths:
  /v3/jobs:
    get:
      operationId: get_jobs
      summary: Get a list of jobs for the user
      description: Returns a list of jobs for the api user
      tags:
      - Jobs
      parameters:
      - name: type
        in: query
        description: Job type to filter by
        required: false
        schema:
          type: string
      - name: reference
        in: query
        description: 'Job reference to filter by. Performs a partial match, eg "partner" would match a reference of "partnerize",

          "dance-partner" and "partner".

          '
        required: false
        schema:
          type: string
      - name: offset
        in: query
        description: Pagination offset
        required: false
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Pagination limit
        required: false
        schema:
          type: integer
          default: 20
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Job task list
                properties:
                  data:
                    type: array
                    items:
                      $schema: http://json-schema.org/draft-07/schema#
                      title: v3 Task Summary Object
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            id:
                              type: string
                            created_at:
                              $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                            started_at:
                              $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                            completed_at:
                              $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                            created_by_uri:
                              type: string
                            created_by:
                              type: string
                            created_by_username:
                              type: string
                            status:
                              $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/status'
                            percentage_complete:
                              type: integer
                            type:
                              type: string
                      example:
                        id: 111111l11
                        created_at: '2018-11-13T20:20:39+00:00'
                        started_at: '2018-11-13T20:20:39+00:00'
                        completed_at: '2018-11-13T20:20:39+00:00'
                        created_by_uri: http://api.partnerize.tech/v3/campaigns/111111l1/conversions/bulk
                        created_by: 1111l111
                        created_by_username: API User
                        status: complete
                        percentage_complete: 100
                        type: conversion_bulk_update
                        hypermedia:
                          links:
                            self: v3/jobs/111111l11
                            tasks: v3/jobs/111111l11/tasks/111111l12
                  hypermedia:
                    properties:
                      pagination:
                        $schema: http://json-schema.org/draft-07/schema#
                        type: object
                        title: v3 Hypermedia Task Pagination
                        properties:
                          total_count:
                            type: integer
                          first_page:
                            type: string
                          last_page:
                            type: string
                          next_page:
                            type:
                            - string
                            - 'null'
                          previous_page:
                            type:
                            - string
                            - 'null'
                        example:
                          total_page_count: 5
                          total_item_count: 5
                          first_page: /jobs?offset=0&limit=100
                          last_page: /jobs?offset=400&limit=100
                          next_page: /jobs?offset=100&limit=100
                          previous_page: null
                example:
                  data:
                  - id: 111111l11
                    created_at: '2018-11-13T20:20:39+00:00'
                    started_at: '2018-11-13T20:20:39+00:00'
                    completed_at: '2018-11-13T20:20:39+00:00'
                    created_by_uri: http://api.partnerize.tech/v3/campaigns/111111l1/conversions/bulk
                    status: complete
                    percentage_complete: 100
                    type: conversion_bulk_update
                    hypermedia:
                      links:
                        self: v3/jobs/111111l11
                        tasks: v3/jobs/111111l11/tasks/111111l112
                  hypermedia:
                    pagination:
                      total_page_count: 5
                      total_item_count: 5
                      first_page: /jobs?offset=0&limit=100
                      last_page: /jobs?offset=400&limit=100
                      next_page: /jobs?offset=100&limit=100
                      previous_page: null
  /v3/jobs/{jobID}:
    get:
      operationId: get_job
      summary: Get a single job
      description: Returns information about a single v3 job by the given ID
      tags:
      - Jobs
      parameters:
      - name: jobID
        in: path
        description: Id of the job
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Job Response
                properties:
                  data:
                    $schema: http://json-schema.org/draft-07/schema#
                    type: object
                    title: v3 Job Object
                    properties:
                      id:
                        type: string
                      reference:
                        type: string
                      created_at:
                        definitions:
                          date-time:
                            type: string
                            format: date-time
                            description: 'ISO8601 format, for example: `"2018-11-13T20:20:39+00:00"`'
                          interval:
                            type: string
                            pattern: ^P(?!$)(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(?=\d+[HMS])(\d+H)?(\d+M)?(\d+S)?)?$
                            description: 'ISO8601 durations format, for example: `"P2DT7H"` (2 days and 7 hours)'
                          between-start-end:
                            type: object
                            required:
                            - start
                            - end
                            properties:
                              start:
                                $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at/definitions/date-time'
                              end:
                                $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at/definitions/date-time'
                            additionalProperties: false
                      started_at:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                      completed_at:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                      created_by:
                        type: string
                      created_by_username:
                        type: string
                      created_by_uri:
                        type: string
                      status:
                        $schema: http://json-schema.org/draft-07/schema#
                        title: v3 Job Statuses
                        type: string
                        enum:
                        - created
                        - active
                        - complete
                        - failed
                      percentage_complete:
                        type: integer
                      item_success_count:
                        type: integer
                      item_error_count:
                        type: integer
                      item_total_count:
                        type: integer
                      type:
                        type: string
                    example:
                      id: 111111l11
                      created_at: '2018-11-13T20:20:39+00:00'
                      started_at: '2018-11-13T20:20:39+00:00'
                      completed_at: '2018-11-13T20:20:39+00:00'
                      created_by_uri: https://api.partnerize.com/v3/campaigns/111111l1/conversions/bulk
                      created_by: 1111l111
                      created_by_username: API User
                      status: complete
                      type: conversion_bulk_update
                      percentage_complete: 100
                      item_success_count: 1
                      item_total_count: 4
                      item_error_count: 3
                  hypermedia:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          self:
                            type: string
                            example: /v3/jobs/111111l11
                          tasks:
                            type: string
                            example: /v3/jobs/111111l11/tasks
  /v3/jobs/{jobID}/tasks:
    get:
      operationId: get_job_tasks
      summary: Get tasks for a job
      description: Returns a list of tasks for a given job
      tags:
      - Jobs
      parameters:
      - name: jobID
        in: path
        description: Id of the job
        required: true
        schema:
          type: string
      - name: offset
        in: query
        description: Pagination offset
        required: false
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Pagination limit
        required: false
        schema:
          type: integer
          default: 20
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Job task list
                properties:
                  data:
                    type: array
                    items:
                      $schema: http://json-schema.org/draft-07/schema#
                      title: v3 Task Summary Object
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            id:
                              type: string
                            status:
                              $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/status'
                            hypermedia:
                              type: object
                              properties:
                                links:
                                  type: string
                      example:
                        id: 111111l11
                        status: complete
                        percentage_complete: 100
                        hypermedia:
                          links:
                            self: v3/jobs/111111l11/tasks/111111l12
                  hypermedia:
                    properties:
                      pagination:
                        $schema: http://json-schema.org/draft-07/schema#
                        type: object
                        title: v3 Hypermedia Task Pagination
                        properties:
                          total_count:
                            type: integer
                          first_page:
                            type: string
                          last_page:
                            type: string
                          next_page:
                            type:
                            - string
                            - 'null'
                          previous_page:
                            type:
                            - string
                            - 'null'
                        example:
                          total_page_count: 5
                          total_item_count: 5
                          first_page: /jobs/111111l11/tasks?offset=0&limit=100
                          last_page: /jobs/111111l11/tasks?offset=400&limit=100
                          next_page: /jobs/111111l11/tasks?offset=100&limit=100
                          previous_page: null
                example:
                  data:
                  - id: 111111l11
                    status: complete
                    hypermedia:
                      links:
                        self: v3/jobs/111111l11/tasks/111111l112
                  hypermedia:
                    pagination:
                      total_page_count: 5
                      total_item_count: 5
                      first_page: /jobs/111111l11/tasks?offset=0&limit=100
                      last_page: /jobs/111111l11/tasks?offset=400&limit=100
                      next_page: /jobs/111111l11/tasks?offset=100&limit=100
                      previous_page: null
  /v3/jobs/{jobID}/tasks/{taskID}:
    get:
      operationId: get_task
      summary: Get detailed task information
      description: Returns detailed information for a given task
      tags:
      - Jobs
      parameters:
      - name: jobID
        in: path
        description: Id of the job
        required: true
        schema:
          type: string
      - name: taskID
        in: path
        description: Id of the task
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Job Task
                properties:
                  data:
                    $schema: http://json-schema.org/draft-07/schema#
                    type: object
                    title: v3 Job Task Object
                    properties:
                      id:
                        type: string
                      job_id:
                        type: string
                      item_success_count:
                        type: integer
                      item_error_count:
                        type: integer
                      item_total_count:
                        type: integer
                      created_at:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                      started_at:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                      completed_at:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                      status:
                        $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/status'
                      result_data:
                        type: string
                    example:
                      id: 111111l11
                      job_id: 111111l12
                      item_success_count: 1
                      item_total_count: 4
                      item_error_count: 3
                      created_at: '2018-11-13T20:20:39+00:00'
                      started_at: '2018-11-13T20:20:39+00:00'
                      completed_at: '2018-11-13T20:20:39+00:00'
                      status: complete
                      result_data: '{Result data generated by the completion of the job}'
  /v3/jobs/{jobID}/replay:
    post:
      operationId: replay_job
      summary: Replay a job
      description: Resubmits a job in to the queue for re-processing. Only jobs of type `conversion_bulk_update` can be replayed.
      tags:
      - Jobs
      parameters:
      - name: jobID
        in: path
        description: Id of the job
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request success
          content:
            application/json:
              schema:
                $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema'
  /v3/jobs/{jobID}/tasks/{taskID}/replay:
    post:
      operationId: replay_job
      summary: Replay a job
      description: Resubmits a task in to the queue for re-processing. Only tasks of type `conversion_bulk_update` can be replayed.
      tags:
      - Jobs
      parameters:
      - name: jobID
        in: path
        description: Id of the job
        required: true
        schema:
          type: string
      - name: taskID
        in: path
        description: Id of the task
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request success
          content:
            application/json:
              schema:
                $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D~1tasks~1%7BtaskID%7D/get/responses/200/content/application~1json/schema'
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
