openapi: 3.2.0
info:
  title: Partnerize Brands Attribution Product Feeds API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- description: 'A Brand may want to offer a selection of Product Feeds to their Partners on a specific Campaign.

    When a Product Feed is created, it will be periodically downloaded and parsed for all Partners who participate on the Campaign to ensure their tracking links are inserted for all anchor links within the Product Feed.

    Any text based file format is supported.'
  name: Product Feeds
paths:
  /campaign/{campaign_id}/feed:
    get:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    feeds:
                    - feed:
                        active: y
                        dynamic: 0
                        feed_id: 1111l13
                        fetch_frequency: 3600
                        filesize: 0
                        last_processed: 1378980455
                        location: http://example.com/feed.xml
                        name: Sample Product Feed
                        updated: 1378980455
              schema:
                properties:
                  feeds:
                    items:
                      $ref: '#/components/schemas/Feed_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Product Feeds
      description: Return the details of all Product Feeds associated with a Campaign.
      operationId: List all Product Feeds
      summary: List all Product Feeds for a Campaign
    post:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '201':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    feeds:
                    - feed:
                        active: y
                        dynamic: 0
                        feed_id: 1111l13
                        fetch_frequency: 3600
                        filesize: 0
                        last_processed: 1378980455
                        location: http://example.com/feed.xml
                        name: Sample Feed
                        updated: 1378980455
              schema:
                properties:
                  feeds:
                    items:
                      $ref: '#/components/schemas/Feed_Wrapper'
                    type: array
                type: object
          description: Created
      tags:
      - Product Feeds
      description: Create one or more Product Feeds against the Campaign entity. Each Product Feed is sent as an array within a top level `feeds` array.
      operationId: Create a Product Feed for a Campaign
      requestBody:
        content:
          application/json:
            schema:
              example:
                feeds:
                - active: y
                  dynamic: 0
                  fetch_frequency: 3600
                  location: http://example.com/feed.xml
                  name: Sample Feed
              properties:
                feeds:
                  items:
                    $ref: '#/components/schemas/Feed'
                  type: array
              required:
              - feeds
              type: object
      summary: Create a Product Feed
    put:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    feeds:
                    - feed:
                        action: update
                        active: y
                        dynamic: 0
                        feed_id: 1111l13
                        fetch_frequency: 3600
                        filesize: 0
                        last_processed: 1378980455
                        location: http://example.com/feed.xml
                        name: Sample Feed
                        updated: 1378980455
              schema:
                properties:
                  feeds:
                    items:
                      $ref: '#/components/schemas/Feed_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Product Feeds
      description: 'Update one or more `feeds` against the Campaign entity. Each Product Feed is sent as an array within a top level `feeds` array and must contain its associated `feed_id` or `location`. As `location` is a unique identifier, it''s not possible to change the location of a feed once created. To update the location, first update the feed and set `active: n`, then create a new feed with the new location.'
      operationId: Update a Campaign Feed
      requestBody:
        content:
          application/json:
            schema:
              example:
                feeds:
                - active: y
                  feed_id: 1111l13
                  fetch_frequency: 3600
                  name: Sample Feed
              properties:
                feeds:
                  items:
                    oneOf:
                    - properties:
                        feed_id:
                          description: ID of the Product Feed
                          type: string
                      type: object
                    - properties:
                        location:
                          description: URL of the feed
                          type: string
                      type: object
                    properties:
                      active:
                        $ref: '#/components/schemas/YesOrNo'
                      fetch_frequency:
                        type: number
                      name:
                        type: string
                    type: object
                  type: array
              required:
              - feeds
              type: object
      summary: Update a Product Feed for a Campaign
components:
  schemas:
    Feed_Wrapper:
      properties:
        feed:
          $ref: '#/components/schemas/Feed'
      type: object
    Feed:
      properties:
        active:
          $ref: '#/components/schemas/YesOrNo'
        dynamic:
          type: number
        feed_id:
          description: ID of the Product Feed
          type: string
        fetch_frequency:
          type: number
        filesize:
          type: number
        last_processed:
          description: UNIX timestamp
          type: number
        location:
          type: string
        name:
          type: string
        updated:
          description: UNIX timestamp
          type: number
      type: object
    YesOrNo:
      enum:
      - y
      - n
      type: string
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
