openapi: 3.2.0
info:
  title: Partnerize Partners Tracking Links API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
tags:
- name: Tracking Links
paths:
  /v2/publishers/<publisher_id>/links:
    get:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.29440 seconds
                    count: 2
                    limit: 200
                    offset: 0
                    links:
                    - id: 1011l10
                      campaign_id: 4d36c720be593
                      description: null
                      destination_url: http://test.com
                      tracking_short_url: https://staging.prf.hn/l/bKVPQEz
                      tracking_url: https://staging.prf.hn/click/camref:cCdTebt4e/pubref:fdghjdkf/destination:http://test.com
                      params:
                      - key: pubref
                        value: fdghjdkf
                      active: true
                    - id: 1011l18
                      campaign_id: '300045'
                      description: null
                      destination_url: http://dfdff
                      tracking_short_url: https://staging.prf.hn/l/GE082EL
                      tracking_url: https://staging.prf.hn/click/camref:i995/pubref:fdfdf/adref:dfdff/destination:http://dfdff
                      params:
                      - key: pubref
                        value: fdfdf
                      - key: adref
                        value: dfdff
                      active: true
                    hypermedia:
                      pagination:
                        total_page_count: 1
                        total_item_count: 1
                        first_page: /v2/publishers/2/links?limit=200&offset=0
                        last_page: /v2/publishers/2/links?limit=200&offset=0
                        next_page: null
                        previous_page: null
              schema:
                properties:
                  links:
                    items:
                      $ref: '#/components/schemas/Link'
                    type: array
                type: object
          description: OK
      tags:
      - Tracking Links
      description: Retrieve tracking links for a given partner. Note, these will only be short links.
      operationId: Retrieve Tracking Links
      summary: Retrieve Tracking Links
    post:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.29440 seconds
                    link:
                      id: 1011l10
                      campaign_id: 4d36c720be593
                      description: null
                      destination_url: http://test.com
                      tracking_short_url: https://staging.prf.hn/l/bKVPQEz
                      tracking_url: https://staging.prf.hn/click/camref:cCdTebt4e/pubref:fdghjdkf/destination:http://test.com
                      params:
                      - key: pubref
                        value: fdghjdkf
                      active: true
              schema:
                properties:
                  link:
                    $ref: '#/components/schemas/Link'
          description: OK
      tags:
      - Tracking Links
      description: Create tracking links for a given partner and campaign.
      operationId: Create Tracking Links
      requestBody:
        content:
          application/json:
            example:
              campaign_id: 4d36c720be593
              description: null
              destination_url: http://test.com
              params:
              - key: pubref
                value: fdghjdkf
              active: true
            schema:
              properties:
                campaign_id:
                  type: string
                description:
                  type: string
                destination_url:
                  type: string
                params:
                  items:
                    $ref: '#/components/schemas/Key_Value_Pair'
                active:
                  type: boolean
              required:
              - campaign_id
              type: object
      summary: Create a Tracking Link
  /v2/publishers/<publisher_id>/links/<link_id>:
    get:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      - description: ID of the tracking link
        example: 1011l10
        in: path
        name: link_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.29440 seconds
                    link:
                      id: 1011l10
                      campaign_id: 4d36c720be593
                      description: null
                      destination_url: http://test.com
                      tracking_short_url: https://staging.prf.hn/l/bKVPQEz
                      tracking_url: https://staging.prf.hn/click/camref:cCdTebt4e/pubref:fdghjdkf/destination:http://test.com
                      params:
                      - key: pubref
                        value: fdghjdkf
                      active: true
              schema:
                properties:
                  link:
                    $ref: '#/components/schemas/Link'
                type: object
          description: OK
      tags:
      - Tracking Links
      description: Retrieve a tracking link.
      operationId: Retrieve a Tracking Link
      summary: Retrieve a Tracking Link
    patch:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      - description: ID of the tracking link
        example: 1011l10
        in: path
        name: link_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    execution_time: 0.29440 seconds
                    link:
                      id: 1011l10
                      campaign_id: 4d36c720be593
                      description: test
                      destination_url: http://test.com
                      tracking_short_url: https://staging.prf.hn/l/bKVPQEz
                      tracking_url: https://staging.prf.hn/click/camref:cCdTebt4e/pubref:fdghjdkf/destination:http://test.com
                      params:
                      - key: pubref
                        value: fdghjdkf
                      active: true
              schema:
                properties:
                  link:
                    $ref: '#/components/schemas/Link'
                type: object
          description: OK
      tags:
      - Tracking Links
      description: Update a tracking link.
      operationId: Update a Tracking Link
      requestBody:
        content:
          application/json:
            example:
              campaign_id: 4d36c720be593
              description: test
              destination_url: http://test.com
              params:
              - key: pubref
                value: fdghjdkf
              active: true
            schema:
              properties:
                campaign_id:
                  type: string
                description:
                  type: string
                destination_url:
                  type: string
                params:
                  items:
                    $ref: '#/components/schemas/Key_Value_Pair'
                active:
                  type: boolean
              type: object
      summary: Update a Tracking Link
components:
  schemas:
    Link:
      properties:
        id:
          type: string
        campaign_id:
          type: string
        description:
          type: string
        destination_url:
          type: string
        tracking_short_url:
          type: string
        tracking_url:
          type: string
        params:
          items:
            $ref: '#/components/schemas/Key_Value_Pair'
        active:
          type: boolean
      type: object
    Key_Value_Pair:
      properties:
        key:
          type: string
        value:
          type: string
      type: object
x-tagGroups:
- name: Partner Management (v1)
  tags:
  - Partner Details
  - Websites
  - Databases
- name: Campaign Management (v1 and v2)
  tags:
  - Brand Discovery (v2)
  - Campaigns (v1)
  - Campaign Invitations (v2)
  - Campaign Requests (v2)
  - Campaign References (v1)
  - Creatives (v1)
  - Feeds (v1)
  - Terms and Conditions
  - Voucher Codes (v1)
- name: Campaign Commissions (v2)
  tags:
  - Attribution
  - Commissions
  - Commission Groups (v1)
  - Promotional Commissions
  - Tiered Commissions
  - Voucher Commissions
- name: Payments (v1)
  tags:
  - Transaction Queries
  - Self-billing
  - Payment Details
  - Available Commission
  - Summary
- name: Tracking Links Management (v2)
  tags:
  - Tracking Links
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Reporting (v1)
  tags:
  - Partner Conversions
  - Partner Clicks
  - Partner Payable
  - Exports
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Countries
  - Currencies
  - Devices
  - Timezones
  - User Contexts
  - Traffic Sources
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Participations (v3)
  tags:
  - Participations
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Brands (v3)
  tags:
  - My Brands
- name: Terms and Conditions (v3)
  tags:
  - Campaign Terms and Conditions
  - Campaign Terms and Conditions Acknowledgments
- name: User (v3)
  tags:
  - Current User
