openapi: 3.2.0
info:
  title: Partnerize Brands Attribution Voucher Codes API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- description: A Voucher references a coupon code, or voucher code which the Brand offers to their customers to usually perform a price discount at the end of the transaction. Specific rules can be set to defined Vouchers ensuring that only valid codes can be used and can also be restricted to specific Partners.
  name: Voucher Codes
paths:
  /campaign/{campaign_id}/voucher_code:
    get:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    voucher_codes:
                    - voucher_code:
                        active: y
                        campaign_id: 10l176
                        commission_groups: []
                        description: ''
                        end_date_time: '2013-09-30 15:00:00'
                        on_expiry: ignore
                        on_invalid_user: ignore
                        start_date_time: '2013-08-31 15:00:00'
                        voucher_code: promocode
                        voucher_code_id: 111111l1000015
              schema:
                properties:
                  voucher_codes:
                    items:
                      $ref: '#/components/schemas/Voucher_Code_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Voucher Codes
      description: View all Voucher Codes associated with the Campaign.
      operationId: List all Voucher Codes
      summary: List all Campaign Voucher Codes
    post:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    voucher_code:
                      active: y
                      campaign_id: 10l176
                      commission_groups: []
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      on_expiry: ignore
                      on_invalid_user: ignore
                      start_date_time: '2013-08-31 15:00:00'
                      voucher_code: promocode
                      voucher_code_id: 111111l1000015
              schema:
                properties:
                  voucher_codes:
                    items:
                      $ref: '#/components/schemas/Voucher_Code_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Voucher Codes
      description: 'Create new Vouchers by passing each Voucher object within a `voucher_codes` array. A `voucher_code` string to define

        the actual code must be passed with each object, and to allocate the Voucher to specific Groups, pass the Group ids

        in a `commission_groups` array.'
      operationId: Create Voucher Codes
      requestBody:
        content:
          application/json:
            schema:
              example:
                voucher_codes:
                - commission_groups: []
                  description: ''
                  end_date_time: '2013-09-30 15:00:00'
                  start_date_time: '2013-08-31 15:00:00'
                  voucher_code: specialoffer69
              properties:
                voucher_codes:
                  items:
                    properties:
                      commission_groups:
                        description: IDs of the commission groups to be associated with the voucher
                        items:
                          type: string
                        type: array
                      description:
                        type: string
                      voucher_code:
                        type: string
                      start_date_time:
                        type: string
                      end_date_time:
                        type: string
                    type: object
                  type: array
              type: object
      summary: Create Voucher Codes
    put:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    voucher_code:
                      active: y
                      campaign_id: 10l176
                      commission_groups: []
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      on_expiry: ignore
                      on_invalid_user: ignore
                      start_date_time: '2013-08-31 15:00:00'
                      voucher_code: promocode
                      voucher_code_id: 111111l1000015
              schema:
                properties:
                  voucher_codes:
                    items:
                      $ref: '#/components/schemas/Voucher_Code_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Voucher Codes
      description: Update Vouchers by referencing the `voucher_code_id` in each Group object within the `voucher_codes` array.
      operationId: Update Voucher Codes
      requestBody:
        content:
          application/json:
            schema:
              example:
                voucher_codes:
                - commission_groups: []
                  description: ''
                  end_date_time: '2013-09-30 15:00:00'
                  start_date_time: '2013-08-31 15:00:00'
                  voucher_code: promocode
                  voucher_code_id: 111111l1000015
              properties:
                voucher_codes:
                  items:
                    properties:
                      voucher_code_id:
                        type: string
                      commission_groups:
                        description: IDs of the commission groups to be associated with the voucher
                        items:
                          type: string
                        type: array
                      description:
                        type: string
                      voucher_code:
                        type: string
                      start_date_time:
                        type: string
                      end_date_time:
                        type: string
                    type: object
                  type: array
              type: object
      summary: Update Voucher Codes
  /campaign/{campaign_id}/voucher_code/{voucher_code_id}:
    get:
      parameters:
      - description: ID of the Campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: ID of the voucher code
        example: 111111l1000015
        in: path
        name: voucher_code_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    voucher_code:
                      active: y
                      campaign_id: 10l176
                      commission_groups: []
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      on_expiry: ignore
                      on_invalid_user: ignore
                      start_date_time: '2013-08-31 15:00:00'
                      voucher_code: promocode
                      voucher_code_id: 111111l1000015
              schema:
                $ref: '#/components/schemas/Voucher_Code_Wrapper'
          description: OK
      tags:
      - Voucher Codes
      description: Outputs the specified Voucher Code.
      operationId: Retrieve a Voucher Code
      summary: Retrieve a Voucher Code
components:
  schemas:
    Commission_Group:
      properties:
        campaign_id:
          description: ID of the campaign
          type: string
        description:
          type: string
        name:
          type: string
        publishers:
          description: IDs of the partners to be associated with the group
          items:
            type: string
          type: array
        active:
          $ref: '#/components/schemas/YesOrNo'
        commission_group_id:
          description: ID of the commission group
          type: string
        last_modified:
          type: string
      required:
      - name
      - campaign_id
      type: object
    Commission_Group_Wrapper:
      properties:
        commission_group:
          $ref: '#/components/schemas/Commission_Group'
      type: object
    YesOrNo:
      enum:
      - y
      - n
      type: string
    Voucher_Code:
      properties:
        commission_groups:
          description: Commission groups associated with the voucher
          items:
            $ref: '#/components/schemas/Commission_Group_Wrapper'
          type: array
        description:
          type: string
        voucher_code:
          type: string
        active:
          $ref: '#/components/schemas/YesOrNo'
        campaign_id:
          description: ID of the Campaign
          type: string
        on_expiry:
          type: string
        on_invalid_user:
          type: string
        voucher_code_id:
          description: ID of the Voucher Code
          type: string
        start_date_time:
          type: string
        end_date_time:
          type: string
      type: object
    Voucher_Code_Wrapper:
      properties:
        voucher_code:
          $ref: '#/components/schemas/Voucher_Code'
      type: object
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
