openapi: 3.2.0
info:
  title: Partnerize Brands Attribution Partner Groups API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- name: Partner Groups
  description: A Campaign owner can organise Partners into Partner Groups, also known as Commission Groups. These Groups can be used for Reporting purposes, Commission offers and Voucher Code allocation.
paths:
  /campaign/{campaign_id}/commission_group:
    get:
      parameters:
      - description: ID of the campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    commission_groups:
                    - commission_group:
                        active: y
                        campaign_id: 10l176
                        commission_group_id: 10l169
                        description: ''
                        end_date_time: '2013-09-30 15:00:00'
                        last_modified: '2015-04-10 01:59:54'
                        name: Fansites 3 percent
                        publishers:
                        - 100l06
                        - 100l08
                        start_date_time: '2013-08-31 15:00:00'
              schema:
                properties:
                  commission_groups:
                    items:
                      $ref: '#/components/schemas/Commission_Group_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Partner Groups
      description: View all Partner (Commission) Groups for a campaign with all associated partners.
      operationId: List Partner Groups
      summary: List all Partner (Commission) Groups for a given campaign
  /campaign/{campaign_id}/commission_group/{commission_group_id}:
    get:
      parameters:
      - description: ID of the campaign
        example: 10l176
        in: path
        name: campaign_id
        required: true
        schema:
          type: string
      - description: ID of the Partner (Commission) group
        example: 10l169
        in: path
        name: commission_group_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    commission_group:
                      active: y
                      campaign_id: 10l176
                      commission_group_id: 10l169
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      last_modified: '2015-04-10 01:59:54'
                      name: Fansites 3 percent
                      publishers:
                      - 100l06
                      - 100l08
                      start_date_time: '2013-08-31 15:00:00'
              schema:
                properties:
                  commission_group:
                    properties:
                      active:
                        enum:
                        - y
                        - n
                        type: string
                      campaign_id:
                        description: ID of the campaign
                        type: string
                      commission_group_id:
                        description: ID of the Partner (Commission) group
                        type: string
                      description:
                        type: string
                      end_date_time:
                        type:
                        - string
                        - 'null'
                      last_modified:
                        type: string
                      name:
                        type: string
                      publishers:
                        description: IDs of the publishers to be associated with the group
                      start_date_time:
                        type:
                        - string
                        - 'null'
                    type: object
                type: object
          description: OK
      tags:
      - Partner Groups
      description: Retrieves the specified Partner (Commission) Group.
      operationId: Retrieve a Partner Group
      summary: Retrieve a Partner (Commission) Group
  /commission_group:
    post:
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    commission_group:
                      active: y
                      campaign_id: 10l176
                      commission_group_id: 10l169
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      last_modified: '2015-04-10 01:59:54'
                      name: Fansites 3 percent
                      publishers:
                      - 100l06
                      - 100l08
                      start_date_time: '2013-08-31 15:00:00'
              schema:
                properties:
                  commission_group:
                    properties:
                      active:
                        enum:
                        - y
                        - n
                        type: string
                      campaign_id:
                        description: ID of the campaign
                        type: string
                      commission_group_id:
                        description: ID of the Partner (Commission) group
                        type: string
                      description:
                        type: string
                      end_date_time:
                        type:
                        - string
                        - 'null'
                      last_modified:
                        type: string
                      name:
                        type: string
                      publishers:
                        description: IDs of the partners to be associated with the group
                      start_date_time:
                        type:
                        - string
                        - 'null'
                    required:
                    - name
                    - campaign_id
                    type: object
                type: object
          description: OK
      tags:
      - Partner Groups
      description: Create new Partner (Commission) Groups. To add Partners into the Partner (Commission) Group pass them in a `publishers` array.
      operationId: Create Partner Groups
      requestBody:
        content:
          application/json:
            schema:
              example:
                commission_groups:
                - campaign_id: 10l176
                  description: ''
                  end_date_time: '2013-09-30 15:00:00'
                  name: Top Sites 2 percent
                  publishers:
                  - 100l06
                  - 100l08
                  start_date_time: '2013-08-31 15:00:00'
              properties:
                commission_groups:
                  type: array
              type: object
      summary: Create Partner (Commission) Groups
    put:
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    commission_group:
                      active: y
                      campaign_id: 10l176
                      commission_group_id: 10l169
                      description: ''
                      end_date_time: '2013-09-30 15:00:00'
                      last_modified: '2015-04-10 01:59:54'
                      name: Fansites 3 percent
                      publishers:
                      - 100l06
                      - 100l08
                      start_date_time: '2013-08-31 15:00:00'
              schema:
                properties:
                  commission_group:
                    properties:
                      active:
                        enum:
                        - y
                        - n
                        type: string
                      campaign_id:
                        description: ID of the campaign
                        type: string
                      commission_group_id:
                        description: ID of the Partner (Commission) group
                        type: string
                      description:
                        type: string
                      end_date_time:
                        type:
                        - string
                        - 'null'
                      last_modified:
                        type: string
                      name:
                        type: string
                      publishers:
                        description: IDs of the partners to be associated with the group
                      start_date_time:
                        type:
                        - string
                        - 'null'
                    required:
                    - name
                    - campaign_id
                    type: object
                type: object
          description: OK
      tags:
      - Partner Groups
      description: Update Partner (Commission) Groups by referencing the `commission_group_id` in each Group object within the `commission_groups` array.
      operationId: Update Partner (Commission) Groups
      requestBody:
        content:
          application/json:
            schema:
              example:
                commission_groups:
                - campaign_id: 10l176
                  commission_group_id: 10l169
                  description: ''
                  end_date_time: '2013-09-30 15:00:00'
                  name: Top Sites 4 percent
                  publishers:
                  - 100l06
                  - 100l08
                  start_date_time: '2013-08-31 15:00:00'
              properties:
                commission_groups:
                  type: array
              type: object
      summary: Update Partner (Commission) Groups
components:
  schemas:
    YesOrNo:
      enum:
      - y
      - n
      type: string
    Commission_Group:
      properties:
        campaign_id:
          description: ID of the campaign
          type: string
        description:
          type: string
        name:
          type: string
        publishers:
          description: IDs of the partners to be associated with the group
          items:
            type: string
          type: array
        active:
          $ref: '#/components/schemas/YesOrNo'
        commission_group_id:
          description: ID of the commission group
          type: string
        last_modified:
          type: string
      required:
      - name
      - campaign_id
      type: object
    Commission_Group_Wrapper:
      properties:
        commission_group:
          $ref: '#/components/schemas/Commission_Group'
      type: object
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
