openapi: 3.2.0
info:
  title: Partnerize Attribution Brands API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- description: 'A User can create one or more Brand accounts. A User can also have access to one or more Brand accounts -

    this is determined by the User''s permissions. A Network admin may choose to grant a User access to multiple

    entities within their Network.'
  name: Brands
paths:
  /user/advertiser:
    get:
      parameters:
      - description: ''
        example: '100'
        in: query
        name: limit
        required: false
        schema:
          type: number
      - description: ''
        example: '0'
        in: query
        name: offset
        required: false
        schema:
          type: number
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    advertisers:
                    - advertiser:
                        account_name: demo_brand
                        address1: Gardegasse 11
                        address2: Top 7
                        address3: London
                        address4: null
                        advertiser_id: 10l110
                        budget_summary_interval: null
                        budget_summary_start_time: null
                        company_name: Partnerize Demo Brand
                        contact_email: someone@partnerize.com
                        country: GB
                        current_balance: null
                        default_currency: GBP
                        display_name: PHG
                        payment_currency: GBP
                        phone: 01595725007
                        phone_area: '+44'
                        postcode: A-101
                        pre_payment: null
                        signup_ip: 178.23.129.160
                        status: a
                        vat_number: GB974997534
                    count: 86
                    execution_time: 0.23640 seconds
                    limit: 100
                    offset: 0
              schema:
                properties:
                  advertisers:
                    items:
                      $ref: '#/components/schemas/Brand_Account_Wrapper'
                    type: array
                  count:
                    type: number
                  execution_time:
                    type: string
                  limit:
                    type: number
                  offset:
                    type: number
                type: object
          description: OK
      tags:
      - Brands
      description: 'One or more Brands can reside on a Network. This endpoint will output a listing of all Brands who reside on

        the Network and the output is contextual based on the permissions of the User making the request to the endpoint.

        A limited Brand schema will be utilised for any Brand that the User does not have appropriate permissions to view.'
      operationId: List all Brands
      summary: List all Brands
    post:
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    advertiser:
                      account_name: demo_brand
                      address1: Gardegasse 11
                      address2: Top 7
                      address3: London
                      address4: null
                      advertiser_id: 10l110
                      budget_summary_interval: null
                      budget_summary_start_time: null
                      company_name: Partnerize Demo Brand
                      contact_email: someone@partnerize.com
                      country: GB
                      current_balance: null
                      default_currency: GBP
                      display_name: PHG
                      payment_currency: GBP
                      phone: 01595725007
                      phone_area: '+44'
                      postcode: A-101
                      pre_payment: null
                      signup_ip: 178.23.129.160
                      status: a
                      vat_number: GB974997534
              schema:
                $ref: '#/components/schemas/Brand_Account_Wrapper'
          description: OK
      tags:
      - Brands
      description: Create a new Brand account attached to the authenticated User.
      operationId: Create Brand Account
      requestBody:
        content:
          application/json:
            schema:
              example:
                account_name: newbrand123
                address1: Gardegasse 11
                address2: Top 7
                address3: London
                address4: null
                company_name: PHG Demo Brand
                country: GB
                display_name: PHG
                phone: 01595725007
                phone_area: '+44'
                postcode: A-101
                signup_ip: 178.23.129.160
              $ref: '#/components/schemas/Brand_Account'
      summary: Create Brand
  /user/advertiser/{advertiser_id}:
    get:
      parameters:
      - description: ID of the brand
        example: 10l110
        in: path
        name: advertiser_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    advertiser:
                      account_name: demo_brand
                      address1: Gardegasse 11
                      address2: Top 7
                      address3: London
                      address4: null
                      advertiser_id: 10l110
                      budget_summary_interval: null
                      budget_summary_start_time: null
                      company_name: Partnerize Demo Brand
                      contact_email: someone@partnerize.com
                      country: GB
                      current_balance: null
                      default_currency: GBP
                      display_name: PHG
                      payment_currency: GBP
                      phone: 01595725007
                      phone_area: '+44'
                      postcode: A-101
                      pre_payment: null
                      signup_ip: 178.23.129.160
                      status: a
                      vat_number: GB974997534
              schema:
                $ref: '#/components/schemas/Brand_Account_Wrapper'
          description: OK
      tags:
      - Brands
      description: Outputs the specified brand.
      operationId: Retrieve a Brand
      summary: Retrieve a Brand
    post:
      parameters:
      - description: ID of the brand
        example: 10l110
        in: path
        name: advertiser_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    advertiser:
                      account_name: demo_brand
                      address1: Gardegasse 11
                      address2: Top 7
                      address3: London
                      address4: null
                      advertiser_id: 10l110
                      advertiser_icon: https://console.partnerize.com/assets/icons/10l110.png
                      budget_summary_interval: null
                      budget_summary_start_time: null
                      company_name: Partnerize Demo Brand
                      contact_email: someone@partnerize.com
                      country: GB
                      current_balance: null
                      default_currency: GBP
                      display_name: PHG
                      payment_currency: GBP
                      phone: 01595725007
                      phone_area: '+44'
                      postcode: A-101
                      pre_payment: null
                      signup_ip: 178.23.129.160
                      status: a
                      vat_number: GB974997534
              schema:
                $ref: '#/components/schemas/Brand_Account_Wrapper'
          description: OK
      tags:
      - Brands
      description: Update the specified Brand.
      operationId: Update a Brand
      requestBody:
        content:
          application/json:
            schema:
              example:
                address1: Gardegasse 11
                address2: Top 7
                address3: London
                address4: null
                advertiser_id: 10l110
                advertiser_icon: http://example.com/path/to/image.png
                company_name: Partnerize Demo Brand
                country: GB
                phone: 01595725007
                phone_area: '+44'
                postcode: A-101
                signup_ip: 178.23.129.160
              properties:
                address1:
                  description: 1st line of the address
                  type: string
                address2:
                  description: 2nd line of the address
                  type:
                  - string
                  - 'null'
                address3:
                  description: 3rd line of the address
                  type:
                  - string
                  - 'null'
                address4:
                  description: 4th line of the address
                  type:
                  - string
                  - 'null'
                advertiser_id:
                  description: ID of the brand
                  type: string
                company_name:
                  type: string
                country:
                  description: Country of the address
                  $ref: '#/components/schemas/Country'
                phone:
                  description: Primary contact telephone number
                  type: string
                phone_area:
                  description: Phone prefix to declare country or region
                  type:
                  - string
                  - 'null'
                postcode:
                  description: Postcode/Zipcode attached to the address
                  type: string
                signup_ip:
                  type: string
              oneOf:
              - properties:
                  advertiser_icon:
                    description: Url of image to download. Supports PNG and JPEG only.
                    type:
                    - string
                    - 'null'
                type: object
              - properties:
                  advertiser_icon_upload:
                    description: Base64 encoded data url of image to upload. Supports PNG and JPEG only.
                    type:
                    - string
                    - 'null'
                type: object
              required:
              - address1
              - country
              - postcode
              - phone
              - signup_ip
              type: object
      summary: Update a Brand
  /v3/network/{networkId}/brands:
    get:
      summary: Get brands for a network
      description: Lists brands for a given network
      tags:
      - Brands
      parameters:
      - name: networkId
        in: path
        description: Network ID to get brands for
        schema:
          type: string
          example: 1111l11
      - name: with
        in: query
        description: Extra data to fetch as a comma seperated list. Currently only accepts "deeplink-domains"
        schema:
          type: string
          example: deeplink-domains
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $ref: '#/paths/~1v3~1brand/get/responses/200/content/application~1json/schema'
      operationId: getV3NetworkByNetworkIdBrands
      x-operation-id-source: derived
  /v3/brand:
    get:
      summary: Get brands for a user
      description: Lists brands the user has access to
      tags:
      - Brands
      parameters:
      - name: network_id
        in: query
        description: A way to filter brands by network
        schema:
          type: string
          example: 1111l11
      - name: with
        in: query
        description: Extra data to fetch as a comma seperated list. Currently only accepts "deeplink-domains"
        schema:
          type: string
          example: deeplink-domains
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Brand list response
                examples:
                - data:
                  - brand_id: 111111l1
                    brand_name: Brand One
                  - brand_id: 111111l2
                    brand_name: Brand Two
                - data:
                  - brand_id: 111111l1
                    brand_name: Brand One
                    deeplink-domains:
                    - domain: onebrand.com
                      brand_id: 111111l1
                      created_by: 111111l1
                      created_at: '2024-07-25T15:10:03+00:00'
                    - domain: shop.onebrand.com
                      brand_id: 111111l1
                      created_by: 111111l1
                      created_at: '2024-07-25T15:10:03+00:00'
      operationId: getV3Brand
      x-operation-id-source: derived
components:
  schemas:
    Brand_Account_Wrapper:
      properties:
        advertiser:
          $ref: '#/components/schemas/Brand_Account'
      type: object
    Status:
      type: string
      enum:
      - a
      - p
      - r
      - n
    Currency:
      enum:
      - GBP
      - USD
      - EUR
      - JPY
      type: string
    Country:
      enum:
      - AD
      - AE
      - AF
      - AG
      - AI
      - AL
      - AM
      - AO
      - AQ
      - AR
      - AS
      - AT
      - AU
      - AW
      - AX
      - AZ
      - BA
      - BB
      - BD
      - BE
      - BF
      - BG
      - BH
      - BI
      - BJ
      - BL
      - BM
      - BN
      - BO
      - BQ
      - BR
      - BS
      - BT
      - BV
      - BW
      - BY
      - BZ
      - CA
      - CC
      - CD
      - CF
      - CG
      - CH
      - CI
      - CK
      - CL
      - CM
      - CN
      - CO
      - CR
      - CU
      - CV
      - CW
      - CX
      - CY
      - CZ
      - DE
      - DJ
      - DK
      - DM
      - DO
      - DZ
      - EC
      - EE
      - EG
      - EH
      - ER
      - ES
      - ET
      - FI
      - FJ
      - FK
      - FM
      - FO
      - FR
      - GA
      - GB
      - GD
      - GE
      - GF
      - GG
      - GH
      - GI
      - GL
      - GM
      - GN
      - GP
      - GQ
      - GR
      - GS
      - GT
      - GU
      - GW
      - GY
      - HK
      - HM
      - HN
      - HR
      - HT
      - HU
      - ID
      - IE
      - IL
      - IM
      - IN
      - IO
      - IQ
      - IR
      - IS
      - IT
      - JE
      - JM
      - JO
      - JP
      - KE
      - KG
      - KH
      - KI
      - KM
      - KN
      - KP
      - KR
      - KW
      - KY
      - KZ
      - LA
      - LB
      - LC
      - LI
      - LK
      - LR
      - LS
      - LT
      - LU
      - LV
      - LY
      - MA
      - MC
      - MD
      - ME
      - MF
      - MG
      - MH
      - MK
      - ML
      - MM
      - MN
      - MO
      - MP
      - MQ
      - MR
      - MS
      - MT
      - MU
      - MV
      - MW
      - MX
      - MY
      - MZ
      - NA
      - NC
      - NE
      - NF
      - NG
      - NI
      - NL
      - 'NO'
      - NP
      - NR
      - NU
      - NZ
      - OM
      - PA
      - PE
      - PF
      - PG
      - PH
      - PK
      - PL
      - PM
      - PN
      - PR
      - PS
      - PT
      - PW
      - PY
      - QA
      - RE
      - RO
      - RS
      - RU
      - RW
      - SA
      - SB
      - SC
      - SD
      - SE
      - SG
      - SH
      - SI
      - SJ
      - SK
      - SL
      - SM
      - SN
      - SO
      - SR
      - SS
      - ST
      - SV
      - SX
      - SY
      - SZ
      - TC
      - TD
      - TF
      - TG
      - TH
      - TJ
      - TK
      - TL
      - TM
      - TN
      - TO
      - TR
      - TT
      - TV
      - TW
      - TZ
      - UA
      - UG
      - UM
      - US
      - UY
      - UZ
      - VA
      - VC
      - VE
      - VG
      - VI
      - VN
      - VU
      - WF
      - WS
      - XK
      - YE
      - YT
      - ZA
      - ZM
      - ZW
      type: string
    Brand_Account:
      properties:
        account_name:
          description: Unique brand account name
          type: string
        address1:
          description: 1st line of the address
          type: string
        address2:
          description: 2nd line of the address
          type:
          - string
          - 'null'
        address3:
          description: 3rd line of the address
          type:
          - string
          - 'null'
        address4:
          description: 4th line of the address
          type:
          - string
          - 'null'
        advertiser_icon:
          description: Url path to image
          type:
          - string
          - 'null'
        advertiser_id:
          description: ID of the brand
          type: string
        budget_summary_interval:
          type:
          - string
          - 'null'
        budget_summary_start_time:
          type:
          - string
          - 'null'
        company_name:
          type: string
        contact_email:
          type: string
        country:
          description: Country of the address
          $ref: '#/components/schemas/Country'
        current_balance:
          type:
          - string
          - 'null'
        default_currency:
          $ref: '#/components/schemas/Currency'
        display_name:
          description: Name shown to publishers under brand campaign management
          type: string
        payment_currency:
          $ref: '#/components/schemas/Currency'
        phone:
          description: Primary contact telephone number
          type: string
        phone_area:
          description: Phone prefix to declare country or region
          type:
          - string
          - 'null'
        postcode:
          description: Postcode/Zipcode attached to the address
          type: string
        pre_payment:
          type:
          - string
          - 'null'
        signup_ip:
          type: string
        status:
          $ref: '#/components/schemas/Status'
        vat_number:
          type:
          - string
          - 'null'
      required:
      - account_name
      - company_name
      - address1
      - country
      - postcode
      - phone
      - signup_ip
      type: object
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
