openapi: 3.2.0
info:
  title: Partnerize Partners Websites API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
tags:
- name: Websites
paths:
  /user/publisher/{publisher_id}/website:
    get:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    websites:
                    - website:
                        active: y
                        primary: n
                        description: Demo Partner website
                        publisher_id: 1l1007802
                        website_country: GB
                        website_id: 11l18694
                        website_name: null
                        website_type: 9
                        website_type_name: PPC
                        website_url: http://www.partnerize.com
                        website_vertical: 10
                        website_vertical_name: Technical
              schema:
                properties:
                  websites:
                    items:
                      $ref: '#/components/schemas/Partner_Website_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Websites
      description: Return the details of all Websites attached to the Partner account.
      operationId: List all Partner Websites
      summary: List all Partner Websites
    post:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    websites:
                    - website:
                        active: y
                        primary: n
                        description: Demo Partner website
                        publisher_id: 1l1007802
                        website_country: GB
                        website_id: 11l18694
                        website_name: null
                        website_type: 9
                        website_type_name: PPC
                        website_url: http://www.partnerize.com
                        website_vertical: 10
                        website_vertical_name: Technical
              schema:
                properties:
                  websites:
                    items:
                      $ref: '#/components/schemas/Partner_Website_Wrapper'
                    type: array
                type: object
          description: OK
      tags:
      - Websites
      description: Create one or more Websites against the Partner entity. Each Website is sent as an array within a top level `websites` array.
      operationId: Create Partner Website
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - example:
                  active: y
                  primary: n
                  description: Demo Partner website
                  website_country: GB
                  website_name: null
                  website_type: 9
                  website_type_name: PPC
                  website_url: http://www.partnerize.com
                  website_vertical: 10
                  website_vertical_name: Technical
                $ref: '#/components/schemas/Partner_Website'
              - example:
                  websites:
                  - active: y
                    primary: n
                    description: Demo Partner website
                    website_country: GB
                    website_name: null
                    website_type: 9
                    website_type_name: PPC
                    website_url: http://www.partnerize.com
                    website_vertical: 10
                    website_vertical_name: Technical
                title: Array of Partner_Websites
                properties:
                  websites:
                    items:
                      $ref: '#/components/schemas/Partner_Website'
                    type: array
                type: object
      summary: Create Partner Website
    put:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    websites:
                    - website:
                        active: y
                        primary: n
                        description: Demo Partner website
                        publisher_id: 1l1007802
                        website_country: GB
                        website_id: 11l18694
                        website_name: null
                        website_type: 9
                        website_type_name: PPC
                        website_url: http://www.partnerize.com
                        website_vertical: 10
                        website_vertical_name: Technical
              schema:
                properties:
                  websites:
                    items:
                      $ref: '#/components/schemas/Partner_Website'
                    type: array
                type: object
          description: OK
      tags:
      - Websites
      description: Update one or more Websites against the Partner entity. Each Website is sent as an array within a top level `websites` array and must contain its associated `website_id`.
      operationId: Update Partner Websites
      requestBody:
        content:
          application/json:
            schema:
              example:
                websites:
                - active: y
                  primary: n
                  description: Demo Partner website
                  website_country: GB
                  website_id: 11l18694
                  website_name: null
                  website_type: 9
                  website_type_name: PPC
                  website_url: http://www.partnerize.com
                  website_vertical: 10
                  website_vertical_name: Technical
              properties:
                websites:
                  items:
                    $ref: '#/components/schemas/Partner_Website'
                  type: array
              type: object
      summary: Update Partner Websites
  /user/publisher/{publisher_id}/website/{website_id}:
    get:
      parameters:
      - description: ID of the partner
        example: 1l1007802
        in: path
        name: publisher_id
        required: true
        schema:
          type: string
      - description: ID of the partner website
        example: 11l18694
        in: path
        name: website_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    website:
                      active: y
                      primary: n
                      description: Demo Partner website
                      publisher_id: 1l1007802
                      website_country: GB
                      website_id: 11l18694
                      website_name: null
                      website_type: 9
                      website_type_name: PPC
                      website_url: http://www.partnerize.com
                      website_vertical: 10
                      website_vertical_name: Technical
              schema:
                $ref: '#/components/schemas/Partner_Website_Wrapper'
                type: object
          description: OK
      tags:
      - Websites
      description: Retrieves the specified partner website.
      operationId: Retrieve a Partner Website
      summary: Retrieve a Partner Website
components:
  schemas:
    Partner_Website_Wrapper:
      properties:
        website:
          allOf:
          - type: object
            properties:
              website_id:
                description: ID of the partner website
                type: string
          - $ref: '#/components/schemas/Partner_Website'
      type: object
    Partner_Website:
      properties:
        publisher_id:
          description: ID of the partner the website belongs to
          type: string
        active:
          $ref: '#/components/schemas/YesOrNo'
        primary:
          $ref: '#/components/schemas/YesOrNo'
        website_country:
          $ref: '#/components/schemas/Country'
        website_name:
          type: string
        website_type:
          type: number
        website_type_name:
          type: string
        website_url:
          type: string
        website_vertical:
          type: number
        website_vertical_name:
          type: string
      required:
      - website_url
      type: object
    Country:
      enum:
      - AD
      - AE
      - AF
      - AG
      - AI
      - AL
      - AM
      - AO
      - AQ
      - AR
      - AS
      - AT
      - AU
      - AW
      - AX
      - AZ
      - BA
      - BB
      - BD
      - BE
      - BF
      - BG
      - BH
      - BI
      - BJ
      - BL
      - BM
      - BN
      - BO
      - BQ
      - BR
      - BS
      - BT
      - BV
      - BW
      - BY
      - BZ
      - CA
      - CC
      - CD
      - CF
      - CG
      - CH
      - CI
      - CK
      - CL
      - CM
      - CN
      - CO
      - CR
      - CU
      - CV
      - CW
      - CX
      - CY
      - CZ
      - DE
      - DJ
      - DK
      - DM
      - DO
      - DZ
      - EC
      - EE
      - EG
      - EH
      - ER
      - ES
      - ET
      - FI
      - FJ
      - FK
      - FM
      - FO
      - FR
      - GA
      - GB
      - GD
      - GE
      - GF
      - GG
      - GH
      - GI
      - GL
      - GM
      - GN
      - GP
      - GQ
      - GR
      - GS
      - GT
      - GU
      - GW
      - GY
      - HK
      - HM
      - HN
      - HR
      - HT
      - HU
      - ID
      - IE
      - IL
      - IM
      - IN
      - IO
      - IQ
      - IR
      - IS
      - IT
      - JE
      - JM
      - JO
      - JP
      - KE
      - KG
      - KH
      - KI
      - KM
      - KN
      - KP
      - KR
      - KW
      - KY
      - KZ
      - LA
      - LB
      - LC
      - LI
      - LK
      - LR
      - LS
      - LT
      - LU
      - LV
      - LY
      - MA
      - MC
      - MD
      - ME
      - MF
      - MG
      - MH
      - MK
      - ML
      - MM
      - MN
      - MO
      - MP
      - MQ
      - MR
      - MS
      - MT
      - MU
      - MV
      - MW
      - MX
      - MY
      - MZ
      - NA
      - NC
      - NE
      - NF
      - NG
      - NI
      - NL
      - 'NO'
      - NP
      - NR
      - NU
      - NZ
      - OM
      - PA
      - PE
      - PF
      - PG
      - PH
      - PK
      - PL
      - PM
      - PN
      - PR
      - PS
      - PT
      - PW
      - PY
      - QA
      - RE
      - RO
      - RS
      - RU
      - RW
      - SA
      - SB
      - SC
      - SD
      - SE
      - SG
      - SH
      - SI
      - SJ
      - SK
      - SL
      - SM
      - SN
      - SO
      - SR
      - SS
      - ST
      - SV
      - SX
      - SY
      - SZ
      - TC
      - TD
      - TF
      - TG
      - TH
      - TJ
      - TK
      - TL
      - TM
      - TN
      - TO
      - TR
      - TT
      - TV
      - TW
      - TZ
      - UA
      - UG
      - UM
      - US
      - UY
      - UZ
      - VA
      - VC
      - VE
      - VG
      - VI
      - VN
      - VU
      - WF
      - WS
      - XK
      - YE
      - YT
      - ZA
      - ZM
      - ZW
      type: string
    YesOrNo:
      enum:
      - y
      - n
      type: string
x-tagGroups:
- name: Partner Management (v1)
  tags:
  - Partner Details
  - Websites
  - Databases
- name: Campaign Management (v1 and v2)
  tags:
  - Brand Discovery (v2)
  - Campaigns (v1)
  - Campaign Invitations (v2)
  - Campaign Requests (v2)
  - Campaign References (v1)
  - Creatives (v1)
  - Feeds (v1)
  - Terms and Conditions
  - Voucher Codes (v1)
- name: Campaign Commissions (v2)
  tags:
  - Attribution
  - Commissions
  - Commission Groups (v1)
  - Promotional Commissions
  - Tiered Commissions
  - Voucher Commissions
- name: Payments (v1)
  tags:
  - Transaction Queries
  - Self-billing
  - Payment Details
  - Available Commission
  - Summary
- name: Tracking Links Management (v2)
  tags:
  - Tracking Links
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Reporting (v1)
  tags:
  - Partner Conversions
  - Partner Clicks
  - Partner Payable
  - Exports
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Countries
  - Currencies
  - Devices
  - Timezones
  - User Contexts
  - Traffic Sources
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Participations (v3)
  tags:
  - Participations
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Brands (v3)
  tags:
  - My Brands
- name: Terms and Conditions (v3)
  tags:
  - Campaign Terms and Conditions
  - Campaign Terms and Conditions Acknowledgments
- name: User (v3)
  tags:
  - Current User
