openapi: 3.2.0
info:
  title: Partnerize Brands Attribution Campaign Conversions API
  version: 1.4.99
  description: '# Introduction


    This is the full external API documentation for the Partnerize API.'
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- name: Campaign Conversions
paths:
  /v3/brand/campaigns/{campaignID}/conversions/bulk:
    post:
      operationId: v3-conversion-bulk-update
      summary: Bulk update of conversions
      tags:
      - Campaign Conversions
      description: 'Allows for conversion update operations to be performed on conversions within a particular campaign. This can be achieved using the `conversion_id`, `conversion_item_id` or `conversion_reference` identifiers depending on what works best in the situation.


        Any changes to `status` at the `conversions` or `conversion_references` level will be applied to all items within that conversion, provided the individual item is allowed to be updated. Should you want to be more explicit with `status` (or any other field) updates then the `conversion_items` key allows this.


        **Note** Only one of the accepted parameters to the payload (`conversions`, `conversion_items`, or `conversion_references`) can be used at once, each allowing a maximum of 100,000 items.


        Deprecates `POST /campaign/{campaignID}/conversion`'
      parameters:
      - name: campaignID
        in: path
        description: Id of the Campaign
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              title: Campaign Conversion Bulk Update Request Object
              definitions:
                job_reference:
                  title: Job Reference
                  description: Optional user provided job reference
                  type: string
                  maxLength: 256
                conversion-update:
                  $id: '#conversion-update'
                  title: Property name is identifier
                  type: object
                  properties:
                    status:
                      type: string
                      enum:
                      - approved
                      - rejected
                      - pending
                      - fraudulent
                    reason:
                      type: string
                      description: Reason to indicate why a conversion or item was updated.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 255
                    ref_partnership_model_id:
                      type: integer
                      description: Partnership model ID.
                    force_commission_recalculation:
                      type: boolean
                      description: Force commission values to be recalculated against commission rules.
                    publisher_reference:
                      type: string
                      description: Reference for publisher.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 256
                    advertiser_reference:
                      type: string
                      description: Reference for advertiser.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 256
                    conversion_reference:
                      type: string
                      description: Reference for conversion.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 256
                    customer_reference:
                      type: string
                      description: Reference for customer.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 256
                    traffic_source_id:
                      type: integer
                      description: Traffic source ID.
                    conversion_metric_id:
                      type: integer
                      description: Conversion meteric ID.
                    customer_type:
                      type: string
                      description: Customer type.
                      enum:
                      - new
                      - existing
                  additionalProperties: false
                conversion-item-update:
                  $id: '#conversion-item-update'
                  title: Property name is identifier
                  type: object
                  properties:
                    status:
                      type: string
                      enum:
                      - approved
                      - rejected
                      - pending
                      - fraudulent
                    item_value:
                      type: number
                      minimum: 0
                      maximum: 99999999.9999
                    reason:
                      type: string
                      description: Reason to indicate why a conversion or item was updated.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 255
                    force_commission_recalculation:
                      type: boolean
                      description: Force commission values to be recalculated against commission rules.
                    display_to_publisher:
                      type: boolean
                      description: Display conversion item to publishers.
                    category:
                      type: string
                      description: Conversion item category.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 128
                    sku:
                      type: string
                      description: Conversion item SKU.
                      pattern: ^[a-zA-Z0-9 :\-_.,;#]+$
                      maxLength: 512
                  additionalProperties: false
              properties:
                conversions:
                  title: conversions
                  type: object
                  additionalProperties:
                    $ref: '#/paths/~1v3~1brand~1campaigns~1%7BcampaignID%7D~1conversions~1bulk/post/requestBody/content/application~1json/schema/definitions/conversion-update'
                  minProperties: 1
                conversion_items:
                  title: conversion items
                  type: object
                  additionalProperties:
                    $ref: '#/paths/~1v3~1brand~1campaigns~1%7BcampaignID%7D~1conversions~1bulk/post/requestBody/content/application~1json/schema/definitions/conversion-item-update'
                  minProperties: 1
                conversion_references:
                  title: conversion references
                  type: object
                  additionalProperties:
                    $ref: '#/paths/~1v3~1brand~1campaigns~1%7BcampaignID%7D~1conversions~1bulk/post/requestBody/content/application~1json/schema/definitions/conversion-update'
                  minProperties: 1
              oneOf:
              - required:
                - conversions
                title: Conversions
                maxProperties: 1
                example:
                  conversions:
                    111111l1:
                      status: approved
                    111111l2:
                      status: rejected
                      reason: cancelled order
              - required:
                - conversion_items
                title: Conversion Items
                maxProperties: 1
                example:
                  conversion_items:
                    111111l3:
                      status: approved
                      item_value: 12.34
                    111111l4:
                      status: rejected
                      reason: cancelled order
              - required:
                - conversion_references
                title: Conversion References
                maxProperties: 1
                example:
                  conversion_references:
                    conversion_ref:
                      status: approved
              additionalProperties: false
      responses:
        '202':
          description: The bulk request was successful and a job spawned
          content:
            application/json:
              schema:
                $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema'
        '400':
          description: "Any errors that can be immediately determined are returned here, anything else will be handled in the job. \n\n# Error codes\nPossible reasons for a failure are listed in the table below.\n\n| Code | Description |\n|-|-|\n| 99B4BC14-8401-4A45-9AF5-CB79E4989C2E | `conversion_ids` supplied with `conversion_references` request, or non-standard IDs used for `conversions`/`conversion_items` |\n"
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: Validation error
                properties:
                  error:
                    $schema: http://json-schema.org/draft-07/schema#
                    type: object
                    title: Standard error object
                    properties:
                      errors:
                        type: array
                        items:
                          $schema: http://json-schema.org/draft-07/schema#
                          type: object
                          title: Standard error object
                          properties:
                            meta:
                              type: object
                              additionalProperties: true
                            property:
                              type: string
                            type:
                              type: string
                            code:
                              type: string
                            message:
                              type: string
                          example:
                            property: title
                            type: validation_error
                            code: campaign_title_unique
                            message: Campaign name 'Carbon Offset 2' already exists
                            meta:
                              campaign_name: Carbon Offset 2
                      code:
                        type: string
                      message:
                        type: string
                example:
                  error:
                    errors:
                    - property: title
                      type: validation
                      code: validation_error
                      message: title is required
                    code: '400'
                    message: Validation error
x-tagGroups:
- name: Networks and Brands Management (v1)
  tags:
  - Networks
  - Network Partners
  - Network Terms and Conditions
  - Brands
- name: Campaign Management (v1)
  tags:
  - Campaigns
  - Participating Partners
  - Partner Groups
  - Custom Terms and Conditions
  - Voucher Codes
  - Creatives
  - Product Feeds
  - Deals
  - Meta Attributes
- name: Payments (v1)
  tags:
  - Campaign Transaction Queries
  - Transaction Query Reasons
  - Invoices
- name: Commissions (v2)
  tags:
  - Commissions
  - Commissions CSV Download
  - Promotional Commissions
  - Voucher Commissions
  - Tiers
  - Partner Commissions
  - Meta Fields
- name: Attribution (v2)
  tags:
  - Attribution
  - Suppressed Code
  - Exclusive Code
  - Preferred Partner
  - In-Cart
  - Split
- name: Partner management (v2)
  tags:
  - Publishers
  - Campaign Requests and Invites
  - Discovery Settings
- name: Communications tool (v2)
  tags:
  - Communications
  - Platform Communications
  - Placeholders
  - Communication Templates
- name: Tracking and Conversions (v3)
  tags:
  - Campaign Conversions
  - Deep link domains
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Background Jobs (v3)
  tags:
  - Jobs
- name: Reporting (v1)
  tags:
  - Brand Conversions
  - Brand Clicks
  - Exports
  - Reporting on Meta data
- name: Fraud
  tags:
  - Incidents
  - Metrics
  - Partner Whitelisting
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Verticals
  - Locales
  - Countries
  - Currencies
  - Currency countries
  - Devices
  - US States
  - Timezones
  - Campaign Extra Fields
  - User Contexts
  - Traffic Sources
  - Website Types
  - Promotional Methods
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Campaigns (v3)
  tags:
  - Campaign v3
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Terms and Conditions (v3)
  tags:
  - Network Terms and Conditions (v3)
  - Network Terms and Conditions Acknowledgments (v3)
- name: Commissions (v3)
  tags:
  - Commission Groups
  - Paid Search Violations
- name: User (v3)
  tags:
  - Current User
