openapi: 3.2.0
info:
  title: Partnerize Tags API
  version: 1.4.99
  contact:
    email: support@partnerize.com
  x-logo:
    url: https://console.partnerize.com/assets/img/network/partnerize/logo.png
    altText: Partnerize
  description: 'Operations tagged Partnerize Tags across 2 of this provider''s published API definitions: partnerize-partners-api-openapi.yml, partnerize-partnerize-tags-api-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- description: Production
  url: https://api.partnerize.com
- description: Local
  url: http://api.partnerize.tech
tags:
- name: Partnerize Tags
  description: 'Partnerize Tags allow the creation, management and automated serving of various Partnerize features into websites.


    All generated Partnerize Tags include a `url` of which can be embedded into websites to serve back the enabled features of that tag in JavaScript content.


    Partnerize Tags only need to be integrated once, allowing features of the tag to be updated at any time using the Partnerize Tags APIs.


    To view available features of the Partnerize Tag, use the List Partnerize Tag Features API.'
paths:
  /v3/partner/partnerize-tags:
    get:
      summary: List Partnerize Tags
      operationId: listPartnerizeTags
      description: Return a list of available Partnerize Tags.
      tags:
      - Partnerize Tags
      parameters:
      - description: ID of the partner to restrict scope of Partnerize Tags to
        example: 111111l8
        in: query
        name: partner_id
        required: false
        schema:
          type: string
      - description: Optional flag to include features as part of the response
        example: true
        in: query
        name: with_features
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Partnerize Tags list
                properties:
                  data:
                    type: array
                    description: List of Partnerize Tags for Partner
                    items:
                      $schema: http://json-schema.org/draft-07/schema#
                      type: object
                      description: Partnerize Tag data
                      properties:
                        id:
                          type: string
                          description: Unique identifier of a Partnerize Tag
                        scope:
                          type: object
                          properties:
                            partner:
                              type: string
                              description: Partner ID for the Partnerize Tag
                        name:
                          type: string
                          description: Human readable identifier of a Partnerize Tag
                        active:
                          type: boolean
                          description: If the tag is not active, the feature content will not be generated for the tag
                        created_at:
                          definitions:
                            date-time:
                              type: string
                              format: date-time
                              description: 'ISO8601 format, for example: `"2018-11-13T20:20:39+00:00"`'
                            interval:
                              type: string
                              pattern: ^P(?!$)(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(?=\d+[HMS])(\d+H)?(\d+M)?(\d+S)?)?$
                              description: 'ISO8601 durations format, for example: `"P2DT7H"` (2 days and 7 hours)'
                            between-start-end:
                              type: object
                              required:
                              - start
                              - end
                              properties:
                                start:
                                  $ref: '#/paths/~1v3~1partner~1partnerize-tags/post/responses/201/content/application~1json%3B%20charset%3Dutf-8/schema/properties/data/properties/created_at/definitions/date-time'
                                end:
                                  $ref: '#/paths/~1v3~1partner~1partnerize-tags/post/responses/201/content/application~1json%3B%20charset%3Dutf-8/schema/properties/data/properties/created_at/definitions/date-time'
                              additionalProperties: false
                        created_by:
                          type: string
                        last_modified_at:
                          $ref: '#/paths/~1v3~1partner~1partnerize-tags/post/responses/201/content/application~1json%3B%20charset%3Dutf-8/schema/properties/data/properties/created_at'
                        last_modified_by:
                          type: string
                        url:
                          type: string
                          description: The publicly accessible URL for the Partnerize Tag for embedding into website content
                example:
                  data:
                  - id: 111111l35
                    scope:
                      partner: 111111l2
                    name: my-tag-website
                    active: true
                    created_at: '2020-07-22T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-07-22T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/tags/file.js
                  - id: 111111l36
                    scope:
                      partner: 111111l2
                    name: my-tag-mobile
                    active: true
                    created_at: '2020-08-08T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-08-08T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/tags/file.js
    post:
      summary: Create Partnerize Tag
      operationId: createPartnerizeTag
      description: 'Generates a new Partnerize Tag for the requested partner. Freshly generated tag will be empty, without any features enabled by default.


        To allow for global propagation, tags will typically be available for use 15 minutes after their generation.'
      tags:
      - Partnerize Tags
      requestBody:
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              title: Partnerize Tag Request
              description: Partnerize Tag Creation Request
              required:
              - name
              - scope
              properties:
                name:
                  type: string
                  description: A name for the new Partnerize Tag
                  minLength: 1
                  maxLength: 255
                scope:
                  type: object
                  properties:
                    partner:
                      type: string
                      description: Partner ID for the new Partnerize Tag
      responses:
        '201':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    data:
                      id: 111111l35
                      scope:
                        partner: 111111l2
                      name: my-tag-website
                      active: true
                      created_at: '2020-07-22T12:23:58.000Z'
                      created_by: 111111l1
                      last_modified_at: '2020-07-22T12:23:58.000Z'
                      last_modified_by: 111111l1
                      url: https://pzapi-kg.com/tags/file.js
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                description: Partnerize Tag data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1partner~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
          description: OK
    servers:
    - description: Production
      url: https://api.partnerize.com
  /v3/partner/partnerize-tags/{partnerizeTagId}:
    get:
      summary: Get Partnerize Tag
      operationId: getPartnerizeTag
      description: Return information about a single Partnerize Tag from the provided ID.
      tags:
      - Partnerize Tags
      parameters:
      - description: ID of the Partnerize Tag to fetch
        example: 111111l3
        in: path
        name: partnerizeTagId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Partnerize Tag single data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1partner~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
                example:
                  data:
                    id: 111111l35
                    scope:
                      partner: 111111l2
                    name: my-tag-website
                    active: true
                    created_at: '2020-07-22T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-07-22T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/tags/file.js
    patch:
      summary: Update Partnerize Tag
      operationId: updatePartnerizeTag
      description: Updates a specific Partnerize Tag.
      tags:
      - Partnerize Tags
      parameters:
      - name: partnerizeTagId
        in: path
        description: The ID of the Partnerize Tag to be updated
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              title: Partnerize Tag Request
              description: Partnerize Tag Patch Request
              properties:
                name:
                  type: string
                  description: A new name for the Partnerize Tag
                  minLength: 1
                  maxLength: 255
                active:
                  type: boolean
                  description: Enables/Disables the tag
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    data:
                      id: 111111l35
                      scope:
                        partner: 111111l2
                      name: my-tag-website
                      active: true
                      created_at: '2020-07-22T12:23:58.000Z'
                      created_by: 111111l1
                      last_modified_at: '2020-07-22T12:23:58.000Z'
                      last_modified_by: 111111l1
                      url: https://pzapi-kg.com/tags/file.js
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                description: Partnerize Tag data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1partner~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
          description: OK
    delete:
      summary: Delete Partnerize Tag
      operationId: deletePartnerizeTag
      description: Deletes a specific Partnerize Tag.
      tags:
      - Partnerize Tags
      parameters:
      - name: partnerizeTagId
        in: path
        description: The ID of the Partnerize Tag to be deleted
        required: true
        schema:
          type: string
      responses:
        '204':
          description: The Partnerize Tag was deleted successfully.
    servers:
    - description: Production
      url: https://api.partnerize.com
  /v3/brand/partnerize-tags:
    servers:
    - description: Production
      url: https://api.partnerize.com
    - description: Local
      url: http://api.partnerize.tech
    get:
      summary: List Partnerize Tags
      operationId: listPartnerizeTags
      description: Return a list of available Partnerize Tags.
      tags:
      - Partnerize Tags
      parameters:
      - description: ID of the brand to restrict scope of Partnerize Tags to
        example: 111111l3
        in: query
        name: brand_id
        required: false
        schema:
          type: string
      - description: Optional flag to include features as part of the response
        example: true
        in: query
        name: with_features
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Partnerize Tags list
                properties:
                  data:
                    type: array
                    description: List of Partnerize Tags for Brand
                    items:
                      $schema: http://json-schema.org/draft-07/schema#
                      type: object
                      description: Partnerize Tag data
                      properties:
                        id:
                          type: string
                          description: Unique identifier of a Partnerize Tag
                        scope:
                          type: object
                          properties:
                            brand:
                              type: string
                              description: Brand ID for the Partnerize Tag
                        name:
                          type: string
                          description: Human readable identifier of a Partnerize Tag
                        active:
                          type: boolean
                          description: If the tag is not active, the feature content will not be generated for the tag
                        created_at:
                          $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                        created_by:
                          type: string
                        last_modified_at:
                          $ref: '#/paths/~1v3~1jobs~1%7BjobID%7D/get/responses/200/content/application~1json/schema/properties/data/properties/created_at'
                        last_modified_by:
                          type: string
                        url:
                          type: string
                          description: The publicly accessible URL for the Partnerize Tag for embedding into website content
                example:
                  data:
                  - id: 111111l35
                    scope:
                      brand: 111111l2
                    name: my-tag-website
                    active: true
                    created_at: '2020-07-22T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-07-22T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/b/1100l12/1011l1.js
                  - id: 111111l36
                    scope:
                      brand: 111111l2
                    name: my-tag-mobile
                    active: true
                    created_at: '2020-08-08T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-08-08T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/b/1100l12/1011l1.js
    post:
      summary: Create Partnerize Tag
      operationId: createPartnerizeTag
      description: 'Generates a new Partnerize Tag for the requested brand. Freshly generated tag will be empty, without any features enabled by default.


        To allow for global propagation, tags will typically be available for use 15 minutes after their generation.'
      tags:
      - Partnerize Tags
      requestBody:
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              title: Partnerize Tag Request
              description: Partnerize Tag Creation Request
              required:
              - name
              - scope
              properties:
                name:
                  type: string
                  description: A name for the new Partnerize Tag
                  minLength: 1
                  maxLength: 255
                scope:
                  type: object
                  properties:
                    brand:
                      type: string
                      description: Brand ID for the Partnerize Tag
      responses:
        '201':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    data:
                      id: 111111l35
                      scope:
                        brand: 111111l2
                      name: my-tag-website
                      active: true
                      created_at: '2020-07-22T12:23:58.000Z'
                      created_by: 111111l1
                      last_modified_at: '2020-07-22T12:23:58.000Z'
                      last_modified_by: 111111l1
                      url: https://pzapi-kg.com/b/1100l12/1011l1.js
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                description: Partnerize Tag data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1brand~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
          description: OK
  /v3/brand/partnerize-tags/{partnerizeTagId}:
    servers:
    - description: Production
      url: https://api.partnerize.com
    - description: Local
      url: http://api.partnerize.tech
    get:
      summary: Get Partnerize Tag
      operationId: getPartnerizeTag
      description: Return information about a single Partnerize Tag from the provided ID.
      tags:
      - Partnerize Tags
      parameters:
      - name: partnerizeTagId
        in: path
        description: The ID of the Partnerize Tag to be returned
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request Success
          content:
            application/json:
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                title: v3 Partnerize Tag single data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1brand~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
                example:
                  data:
                    id: 111111l35
                    scope:
                      brand: 111111l2
                    name: my-tag-website
                    active: true
                    created_at: '2020-07-22T12:23:58.000Z'
                    created_by: 111111l1
                    last_modified_at: '2020-07-22T12:23:58.000Z'
                    last_modified_by: 111111l1
                    url: https://pzapi-kg.com/b/1100l12/1011l1.js
    patch:
      summary: Update Partnerize Tag
      operationId: updatePartnerizeTag
      description: Updates a specific Partnerize Tag.
      tags:
      - Partnerize Tags
      parameters:
      - name: partnerizeTagId
        in: path
        description: The ID of the Partnerize Tag to be updated
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              title: Partnerize Tag Request
              description: Partnerize Tag Patch Request
              properties:
                name:
                  type: string
                  description: A new name for the Partnerize Tag
                  minLength: 1
                  maxLength: 255
                active:
                  type: boolean
                  description: Enables/Disables the tag
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              examples:
                response:
                  value:
                    data:
                      id: 111111l35
                      scope:
                        brand: 111111l2
                      name: my-tag-website
                      active: true
                      created_at: '2020-07-22T12:23:58.000Z'
                      created_by: 111111l1
                      last_modified_at: '2020-07-22T12:23:58.000Z'
                      last_modified_by: 111111l1
                      url: https://pzapi-kg.com/b/1100l12/1011l1.js
              schema:
                $schema: http://json-schema.org/draft-07/schema#
                type: object
                description: Partnerize Tag data
                properties:
                  data:
                    type: object
                    $ref: '#/paths/~1v3~1brand~1partnerize-tags/get/responses/200/content/application~1json/schema/properties/data/items'
          description: OK
    delete:
      summary: Delete Partnerize Tag
      operationId: deletePartnerizeTag
      description: Deletes a specific Partnerize Tag.
      tags:
      - Partnerize Tags
      parameters:
      - name: partnerizeTagId
        in: path
        description: The ID of the Partnerize Tag to be deleted
        required: true
        schema:
          type: string
      responses:
        '204':
          description: The Partnerize Tag was deleted successfully.
x-refined-from:
- partnerize-partners-api-openapi.yml
- partnerize-partnerize-tags-api-openapi.yml
x-tagGroups:
- name: Partner Management (v1)
  tags:
  - Partner Details
  - Websites
  - Databases
- name: Campaign Management (v1 and v2)
  tags:
  - Brand Discovery (v2)
  - Campaigns (v1)
  - Campaign Invitations (v2)
  - Campaign Requests (v2)
  - Campaign References (v1)
  - Creatives (v1)
  - Feeds (v1)
  - Terms and Conditions
  - Voucher Codes (v1)
- name: Campaign Commissions (v2)
  tags:
  - Attribution
  - Commissions
  - Commission Groups (v1)
  - Promotional Commissions
  - Tiered Commissions
  - Voucher Commissions
- name: Payments (v1)
  tags:
  - Transaction Queries
  - Self-billing
  - Payment Details
  - Available Commission
  - Summary
- name: Tracking Links Management (v2)
  tags:
  - Tracking Links
- name: Background Jobs (v1)
  tags:
  - Jobs (v1)
- name: Reporting (v1)
  tags:
  - Partner Conversions
  - Partner Clicks
  - Partner Payable
  - Exports
- name: Analytics (v3)
  tags:
  - Introduction
  - Tutorials
  - Clicks
  - Conversions
  - Impressions
- name: Reference (v1)
  tags:
  - Countries
  - Currencies
  - Devices
  - Timezones
  - User Contexts
  - Traffic Sources
  - Conversion Types
  - Conversion Metrics
  - Partnership Models
- name: Participations (v3)
  tags:
  - Participations
- name: Partnerize Tags (v3)
  tags:
  - Partnerize Tags
  - Partnerize Tag Features
- name: Brands (v3)
  tags:
  - My Brands
- name: Terms and Conditions (v3)
  tags:
  - Campaign Terms and Conditions
  - Campaign Terms and Conditions Acknowledgments
- name: User (v3)
  tags:
  - Current User
